name: My Test GA
on: 
  pull_request:
    branches: [test-*]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a github event."
      - run: echo "ğŸ This job's status is done."
